#server:
#  port: 8082
#databases:
#  - user: admin
#    password: admin
#    host: localhost
#    dbName: BaseGo
#  - user: order
#    password: admin
#    host: localhost
#    dbName: Order
#security:
#  jwt:
#    secretKey: 123

server:
  port: 8082
  mode: "dev"
postgres:
  host: 127.0.0.1 #postgres
  port: 5432
  username: admin #admin
  password: 123123
  dbname: go_database
  sslmode: disable
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  file_log_name:  "./storages/logs/development.xxx.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: redis #localhost
  port: 6379
  password:
  database: 0